# Generated by Django 5.0.6 on 2024-07-04 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museodataproto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artpiece',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='artpiece',
            name='style',
        ),
        migrations.AddField(
            model_name='artpiece',
            name='genres',
            field=models.ManyToManyField(blank=True, to='museodataproto.genre'),
        ),
        migrations.AddField(
            model_name='artpiece',
            name='styles',
            field=models.ManyToManyField(blank=True, to='museodataproto.style'),
        ),
    ]
