# Generated by Django 5.0.6 on 2024-07-04 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('museodataproto', '0003_artpiece_notes_galleryartpiece_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galleryartpiece',
            old_name='curator_notes',
            new_name='notes',
        ),
    ]
